/**
 * Client-specific design directions (pure layer).
 *
 * Two clients in the same trade should never end up with the same-looking
 * website. This module derives a set of complete visual identities — palette,
 * type, backdrop, section motion and overall styling attitude — and ranks them
 * for the specific business, so the builder can offer real choices instead of
 * one template.
 *
 * Everything returned is expressed as validated agent actions (theme colours,
 * allowlisted backdrops, allowlisted section effects), so applying a direction
 * is snapshotted and reversible like any other builder change.
 */

import type { AgentAction } from "@/lib/site-agent";
import type { BackdropId, SectionEffectId } from "@/lib/site-effects";
import type { ContentPage } from "@/lib/website-content";
import { siteTone } from "@/lib/site-theme";

export type DesignDirection = {
  id: string;
  name: string;
  /** One line the owner understands. */
  mood: string;
  /** Who it suits. */
  bestFor: string;
  primary: string;
  secondary: string;
  accent: string;
  font: string;
  fontNote: string;
  backdrop: BackdropId;
  heroEffect: SectionEffectId;
  ctaEffect: SectionEffectId;
  formEffect: SectionEffectId;
  bodyEffect: SectionEffectId;
  /** Industry words this direction is written for. */
  affinity: string[];
};

export const DESIGN_DIRECTIONS: DesignDirection[] = [
  {
    id: "luxury-gold",
    name: "Luxury gold",
    mood: "Deep black, warm gold, generous space. Feels expensive before a word is read.",
    bestFor: "High-ticket work where trust and price sit together",
    primary: "#d4a544",
    secondary: "#0b0b0d",
    accent: "#f2d69b",
    font: "Playfair Display",
    fontNote: "Editorial serif headings, quiet body text",
    backdrop: "spotlight",
    heroEffect: "float_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: [
      "roof",
      "remodel",
      "landscap",
      "interior",
      "design",
      "law",
      "dental",
      "med",
      "real estate",
    ],
  },
  {
    id: "modern-clean",
    name: "Modern clean",
    mood: "Cool blues, crisp edges, everything easy to scan on a phone.",
    bestFor: "Straightforward services where speed and clarity win the job",
    primary: "#3b82f6",
    secondary: "#0f172a",
    accent: "#93c5fd",
    font: "Inter",
    fontNote: "Neutral, highly readable at every size",
    backdrop: "grid",
    heroEffect: "rise",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["clean", "plumb", "hvac", "it", "tech", "account", "insur", "moving"],
  },
  {
    id: "bold-trade",
    name: "Bold trade",
    mood: "Heavy headlines, high-contrast red and steel. Looks like it gets the job done.",
    bestFor: "Emergency and hard-graft trades competing on speed",
    primary: "#e0402c",
    secondary: "#141416",
    accent: "#ffb703",
    font: "Archivo Black",
    fontNote: "Big impact headings, tight body copy",
    backdrop: "gradient_mesh",
    heroEffect: "tilt_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: [
      "tow",
      "emergency",
      "restoration",
      "demolition",
      "concrete",
      "weld",
      "auto",
      "mechanic",
      "pest",
    ],
  },
  {
    id: "minimal-quiet",
    name: "Minimal quiet",
    mood: "Almost no decoration. Words, space and one clear button.",
    bestFor: "Professional services where calm equals competence",
    primary: "#6b7f6e",
    secondary: "#121513",
    accent: "#cfe0d3",
    font: "Manrope",
    fontNote: "Soft geometric sans, wide spacing",
    backdrop: "none",
    heroEffect: "rise",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["consult", "coach", "therap", "wellness", "yoga", "book keep", "financ"],
  },
  {
    id: "futuristic",
    name: "Futuristic",
    mood: "Aurora light, glass panels, subtle 3D depth. Looks years ahead of the competition.",
    bestFor: "Businesses selling new technology or premium installs",
    primary: "#8b5cf6",
    secondary: "#0a0a13",
    accent: "#22d3ee",
    font: "Space Grotesk",
    fontNote: "Technical sans with character",
    backdrop: "aurora",
    heroEffect: "float_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "parallax_slow",
    affinity: [
      "solar",
      "smart",
      "security",
      "ev",
      "energy",
      "automation",
      "audio",
      "camera",
      "network",
    ],
  },
  {
    id: "night-sky",
    name: "Night sky",
    mood: "Starfield behind deep navy, gold accents. Memorable without shouting.",
    bestFor: "Anyone who wants to be remembered after one visit",
    primary: "#c9a227",
    secondary: "#080c18",
    accent: "#8ea8d8",
    font: "Sora",
    fontNote: "Modern sans, confident headings",
    backdrop: "stars",
    heroEffect: "float_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["event", "photo", "wedding", "entertain", "music", "bar", "restaur"],
  },
  {
    id: "corporate-steel",
    name: "Corporate steel",
    mood: "Navy, graphite and structure. Reads as established and safe to hire.",
    bestFor: "Commercial contracts and bigger buyers",
    primary: "#2563a5",
    secondary: "#101418",
    accent: "#9db4cc",
    font: "IBM Plex Sans",
    fontNote: "Institutional, dependable",
    backdrop: "grid",
    heroEffect: "rise",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: [
      "commercial",
      "industrial",
      "facilit",
      "janitor",
      "logistic",
      "construct",
      "engineer",
    ],
  },
  {
    id: "warm-craft",
    name: "Warm craft",
    mood: "Terracotta and clay tones, handmade feel, friendly wording.",
    bestFor: "Family businesses where people hire the person",
    primary: "#c2703d",
    secondary: "#17110d",
    accent: "#f0c9a6",
    font: "Lora",
    fontNote: "Warm serif headings, easy body text",
    backdrop: "nebula",
    heroEffect: "tilt_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: [
      "bake",
      "florist",
      "salon",
      "groom",
      "child",
      "care",
      "farm",
      "carpent",
      "furniture",
    ],
  },
  {
    id: "editorial",
    name: "Editorial",
    mood: "Magazine layout energy: big type, strong photography, lots of air.",
    bestFor: "Businesses with great photos of their own work",
    primary: "#e8e3d9",
    secondary: "#0d0d0d",
    accent: "#c9a227",
    font: "Instrument Serif",
    fontNote: "Display serif headlines, plain body",
    backdrop: "spotlight",
    heroEffect: "parallax_slow",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["architect", "stage", "paint", "tile", "stone", "pool", "garden", "photo"],
  },
  {
    id: "fresh-green",
    name: "Fresh green",
    mood: "Living greens and daylight. Feels clean, outdoor and healthy.",
    bestFor: "Outdoor, eco and cleaning work",
    primary: "#3f9d5a",
    secondary: "#0c1410",
    accent: "#bdf0c8",
    font: "Figtree",
    fontNote: "Friendly rounded sans",
    backdrop: "gradient_mesh",
    heroEffect: "rise",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["lawn", "tree", "garden", "eco", "green", "solar", "clean", "wash", "septic"],
  },
  {
    id: "pure-white",
    name: "Pure white",
    mood: "Bright white space, black type, one strong colour. Reads instantly on any phone.",
    bestFor: "Anyone who wants to look clean, modern and easy to trust",
    primary: "#111827",
    secondary: "#ffffff",
    accent: "#2563eb",
    font: "Inter",
    fontNote: "Neutral, highly readable at every size",
    backdrop: "none",
    heroEffect: "rise",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["clean", "dental", "med", "law", "account", "consult", "real estate", "insur"],
  },
  {
    id: "coastal-blue",
    name: "Coastal blue",
    mood: "Daylight blues on white. Calm, dependable, easy on the eye.",
    bestFor: "Home services where reassurance closes the job",
    primary: "#1d4ed8",
    secondary: "#f6f9ff",
    accent: "#0ea5e9",
    font: "Figtree",
    fontNote: "Friendly rounded sans",
    backdrop: "gradient_mesh",
    heroEffect: "rise",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["plumb", "pool", "wash", "clean", "hvac", "water", "roof", "window"],
  },
  {
    id: "deep-navy",
    name: "Deep navy",
    mood: "Rich navy with a bright signal blue. Serious money, modern edges.",
    bestFor: "Commercial buyers and bigger contracts",
    primary: "#38bdf8",
    secondary: "#0b1220",
    accent: "#7dd3fc",
    font: "IBM Plex Sans",
    fontNote: "Institutional, dependable",
    backdrop: "grid",
    heroEffect: "float_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["commercial", "security", "it", "tech", "engineer", "logistic", "finance"],
  },
  {
    id: "soft-sand",
    name: "Soft sand",
    mood: "Warm off-white, clay accents, unhurried. Feels handmade and local.",
    bestFor: "Family businesses and care work",
    primary: "#a3541f",
    secondary: "#fbf7f1",
    accent: "#d99b5b",
    font: "Lora",
    fontNote: "Warm serif headings, easy body text",
    backdrop: "none",
    heroEffect: "rise",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["care", "child", "salon", "groom", "bake", "florist", "interior", "furniture"],
  },
  {
    id: "signal-orange",
    name: "Signal orange",
    mood: "White page, hot orange buttons. Impossible to miss the next step.",
    bestFor: "Fast-response trades that live on phone calls",
    primary: "#ea580c",
    secondary: "#fffdfa",
    accent: "#f59e0b",
    font: "Archivo Black",
    fontNote: "Big impact headings, tight body copy",
    backdrop: "none",
    heroEffect: "tilt_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["tow", "emergency", "lock", "garage", "auto", "mechanic", "pest", "moving"],
  },
  {
    id: "clinic-teal",
    name: "Clinic teal",
    mood: "Clean white with clinical teal. Hygienic, precise, calm.",
    bestFor: "Health, dental and anything where cleanliness sells",
    primary: "#0f766e",
    secondary: "#f5fbfa",
    accent: "#14b8a6",
    font: "Manrope",
    fontNote: "Soft geometric sans, wide spacing",
    backdrop: "none",
    heroEffect: "rise",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["dental", "med", "clinic", "therap", "wellness", "clean", "sanit", "vet"],
  },
  {
    id: "slate-mono",
    name: "Slate mono",
    mood: "Grey-on-white, almost no colour, all structure. Quietly expensive.",
    bestFor: "Design-led and professional services",
    primary: "#0f172a",
    secondary: "#f4f5f7",
    accent: "#64748b",
    font: "Space Grotesk",
    fontNote: "Technical sans with character",
    backdrop: "none",
    heroEffect: "parallax_slow",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["architect", "design", "consult", "photo", "stone", "tile", "carpent"],
  },
  {
    id: "orchard-green",
    name: "Orchard green",
    mood: "White daylight with deep garden green. Outdoor, healthy, well-kept.",
    bestFor: "Lawn, tree, garden and eco work",
    primary: "#166534",
    secondary: "#f7fbf5",
    accent: "#4ade80",
    font: "Figtree",
    fontNote: "Friendly rounded sans",
    backdrop: "gradient_mesh",
    heroEffect: "rise",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["lawn", "tree", "garden", "landscap", "eco", "green", "farm", "septic"],
  },
  {
    id: "violet-studio",
    name: "Violet studio",
    mood: "Soft white with electric violet. Creative, current, memorable.",
    bestFor: "Businesses that want to look nothing like their competitors",
    primary: "#6d28d9",
    secondary: "#faf8ff",
    accent: "#a855f7",
    font: "Sora",
    fontNote: "Modern sans, confident headings",
    backdrop: "aurora",
    heroEffect: "float_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "parallax_slow",
    affinity: ["event", "photo", "music", "brand", "market", "salon", "studio", "wedding"],
  },
  {
    id: "ink-paper",
    name: "Ink on paper",
    mood: "Off-white page, black serif headlines, hairline rules. Swiss and self-assured.",
    bestFor: "Advisors and studios who sell judgement, not noise",
    primary: "#141414",
    secondary: "#f6f4ef",
    accent: "#b4622f",
    font: "Libre Baskerville",
    fontNote: "Classic serif headings, plain body",
    backdrop: "none",
    heroEffect: "parallax_slow",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["law", "account", "consult", "architect", "financ", "notary", "estate"],
  },
  {
    id: "midnight-emerald",
    name: "Midnight emerald",
    mood: "Near-black with deep emerald and glass panels. Quietly high-end.",
    bestFor: "Premium installs and members-only feeling services",
    primary: "#10b981",
    secondary: "#07100d",
    accent: "#a7f3d0",
    font: "Outfit",
    fontNote: "Geometric sans, clean headings",
    backdrop: "aurora",
    heroEffect: "float_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "parallax_slow",
    affinity: ["solar", "energy", "smart", "spa", "wellness", "golf", "marine", "landscap"],
  },
  {
    id: "concrete-mono",
    name: "Concrete",
    mood: "Raw grey surfaces, oversized type, industrial confidence.",
    bestFor: "Construction, fabrication and heavy trades",
    primary: "#f4f4f5",
    secondary: "#1b1b1d",
    accent: "#facc15",
    font: "Bebas Neue",
    fontNote: "Tall condensed headings, plain body",
    backdrop: "grid",
    heroEffect: "tilt_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["construct", "concrete", "weld", "demolition", "scaffold", "industrial", "paving"],
  },
  {
    id: "cream-editorial",
    name: "Cream editorial",
    mood: "Warm cream paper, large serif headlines, generous margins.",
    bestFor: "Interiors, weddings and anything photographed beautifully",
    primary: "#1f1a16",
    secondary: "#f7f1e6",
    accent: "#9a6b3f",
    font: "Cormorant Garamond",
    fontNote: "Elegant high-contrast serif",
    backdrop: "none",
    heroEffect: "parallax_slow",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["wedding", "interior", "florist", "photo", "event", "bridal", "cake", "boutique"],
  },
  {
    id: "electric-noir",
    name: "Electric noir",
    mood: "Black with one electric accent and glowing buttons. Nightlife energy.",
    bestFor: "Bars, studios, detailing and anything after dark",
    primary: "#f43f5e",
    secondary: "#0a0a0c",
    accent: "#fb7185",
    font: "Syne",
    fontNote: "Sculptural display sans",
    backdrop: "spotlight",
    heroEffect: "float_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "shine",
    affinity: ["detail", "barber", "tattoo", "bar", "club", "gym", "fitness", "music"],
  },
  {
    id: "sunrise-warm",
    name: "Sunrise",
    mood: "Warm white with sunrise amber. Optimistic and approachable.",
    bestFor: "Family-facing services and local favourites",
    primary: "#b45309",
    secondary: "#fffaf3",
    accent: "#f59e0b",
    font: "Plus Jakarta Sans",
    fontNote: "Rounded, friendly, very legible",
    backdrop: "gradient_mesh",
    heroEffect: "rise",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["bake", "cafe", "child", "care", "school", "tutor", "pet", "groom"],
  },
  {
    id: "harbour-slate",
    name: "Harbour slate",
    mood: "Cool slate with a steel blue signal. Dependable, no drama.",
    bestFor: "Maintenance contracts and repeat-business trades",
    primary: "#334e68",
    secondary: "#f2f5f8",
    accent: "#2f9bd1",
    font: "Work Sans",
    fontNote: "Neutral workhorse sans",
    backdrop: "none",
    heroEffect: "rise",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["hvac", "plumb", "electric", "facilit", "janitor", "marine", "dock", "window"],
  },
  {
    id: "forest-lodge",
    name: "Forest lodge",
    mood: "Deep forest green, warm wood accents, outdoors in the evening.",
    bestFor: "Tree work, cabins, outdoor trades and rural businesses",
    primary: "#84cc16",
    secondary: "#0d1410",
    accent: "#d9f99d",
    font: "Fraunces",
    fontNote: "Characterful serif with warmth",
    backdrop: "nebula",
    heroEffect: "parallax_slow",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["tree", "farm", "ranch", "hunt", "outdoor", "cabin", "firewood", "landscap"],
  },
  {
    id: "clinical-white",
    name: "Clinical white",
    mood: "Pure white, thin borders, one calm blue. Reads as careful and safe.",
    bestFor: "Clinics, labs and anything regulated",
    primary: "#1e5eb8",
    secondary: "#ffffff",
    accent: "#60a5fa",
    font: "Public Sans",
    fontNote: "Plain-spoken institutional sans",
    backdrop: "none",
    heroEffect: "rise",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["clinic", "dental", "med", "lab", "vet", "optic", "pharma", "therap"],
  },
  {
    id: "obsidian-copper",
    name: "Obsidian copper",
    mood: "Black stone with copper detailing. Craft at a high price point.",
    bestFor: "Bespoke makers and premium renovation",
    primary: "#c2703d",
    secondary: "#0c0b0a",
    accent: "#eab676",
    font: "Marcellus",
    fontNote: "Refined roman capitals",
    backdrop: "spotlight",
    heroEffect: "float_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "shine",
    affinity: ["remodel", "kitchen", "cabinet", "stone", "tile", "furniture", "carpent", "forge"],
  },
  {
    id: "sky-minimal",
    name: "Sky minimal",
    mood: "Pale sky gradient, almost no chrome, one obvious action.",
    bestFor: "Simple booking-led services",
    primary: "#0369a1",
    secondary: "#f4fafe",
    accent: "#38bdf8",
    font: "Jost",
    fontNote: "Geometric sans with a light feel",
    backdrop: "gradient_mesh",
    heroEffect: "rise",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["clean", "wash", "pool", "window", "air", "duct", "laundry", "courier"],
  },
  {
    id: "carbon-lime",
    name: "Carbon lime",
    mood: "Carbon black with a lime signal. Modern, technical, fast.",
    bestFor: "Auto, performance and technical installs",
    primary: "#bef264",
    secondary: "#0b0d0b",
    accent: "#65a30d",
    font: "Chivo",
    fontNote: "Tight grotesque, strong numerals",
    backdrop: "grid",
    heroEffect: "tilt_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["auto", "tyre", "tire", "perform", "ev", "bike", "mechanic", "fleet"],
  },
  {
    id: "rose-atelier",
    name: "Rose atelier",
    mood: "Soft blush surfaces with deep plum type. Gentle and considered.",
    bestFor: "Beauty, bridal and boutique services",
    primary: "#9d174d",
    secondary: "#fdf3f6",
    accent: "#f472b6",
    font: "DM Serif Display",
    fontNote: "High-contrast display serif",
    backdrop: "none",
    heroEffect: "rise",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["salon", "beauty", "nail", "lash", "bridal", "spa", "boutique", "aesthetic"],
  },
  {
    id: "steel-amber",
    name: "Steel amber",
    mood: "Graphite panels with amber warning-light accents. Trade-strong.",
    bestFor: "Emergency callouts and 24/7 services",
    primary: "#f59e0b",
    secondary: "#15171a",
    accent: "#fcd34d",
    font: "Oswald",
    fontNote: "Condensed headings that shout clearly",
    backdrop: "spotlight",
    heroEffect: "tilt_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["emergency", "tow", "lock", "restoration", "flood", "storm", "boiler", "sewer"],
  },
  {
    id: "linen-sage",
    name: "Linen sage",
    mood: "Linen background, sage green, unhurried spacing. Calm competence.",
    bestFor: "Wellness, therapy and slow-craft businesses",
    primary: "#4f6f52",
    secondary: "#f6f6f1",
    accent: "#a3b899",
    font: "Spectral",
    fontNote: "Readable literary serif",
    backdrop: "none",
    heroEffect: "parallax_slow",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["therap", "yoga", "massage", "wellness", "counsel", "midwife", "doula", "retreat"],
  },
  {
    id: "indigo-glass",
    name: "Indigo glass",
    mood: "Deep indigo with frosted panels and soft depth. Software-grade polish.",
    bestFor: "Tech-forward and subscription services",
    primary: "#6366f1",
    secondary: "#0a0b18",
    accent: "#a5b4fc",
    font: "Geist",
    fontNote: "Precise modern sans",
    backdrop: "aurora",
    heroEffect: "float_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "parallax_slow",
    affinity: ["it", "tech", "software", "saas", "network", "data", "market", "agency"],
  },
  {
    id: "brick-heritage",
    name: "Brick heritage",
    mood: "Brick red on warm grey, established-since energy.",
    bestFor: "Long-standing local firms",
    primary: "#9f2d24",
    secondary: "#f4f1ed",
    accent: "#c98a52",
    font: "Merriweather",
    fontNote: "Sturdy serif built for reading",
    backdrop: "none",
    heroEffect: "rise",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["mason", "brick", "chimney", "restoration", "heritage", "butcher", "hardware"],
  },
  {
    id: "arctic-chrome",
    name: "Arctic chrome",
    mood: "Icy white-blues with chrome edges. Precise and premium.",
    bestFor: "Refrigeration, medical devices and precision work",
    primary: "#0e7490",
    secondary: "#f2f8fb",
    accent: "#22d3ee",
    font: "Urbanist",
    fontNote: "Clean low-contrast sans",
    backdrop: "gradient_mesh",
    heroEffect: "rise",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["refrig", "cold", "hvac", "air", "device", "calibrat", "precision", "clean room"],
  },
  {
    id: "velvet-plum",
    name: "Velvet plum",
    mood: "Deep plum with soft glow. Indulgent without being loud.",
    bestFor: "Hospitality, private events and treatments",
    primary: "#a855f7",
    secondary: "#120a1a",
    accent: "#e9d5ff",
    font: "Epilogue",
    fontNote: "Elegant variable sans",
    backdrop: "nebula",
    heroEffect: "float_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "shine",
    affinity: ["event", "hotel", "hospital", "lounge", "spa", "cater", "wine", "private"],
  },
  {
    id: "bold-bricolage",
    name: "Bold bricolage",
    mood: "Oversized expressive headings on bright white. Confident and current.",
    bestFor: "Brands that want to look brand-new",
    primary: "#111111",
    secondary: "#fefefe",
    accent: "#ff5a1f",
    font: "Bricolage Grotesque",
    fontNote: "Expressive display grotesque",
    backdrop: "none",
    heroEffect: "tilt_3d",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["brand", "agency", "market", "studio", "design", "startup", "coach", "creator"],
  },
  {
    id: "desert-clay",
    name: "Desert clay",
    mood: "Sandstone and clay with soft shadows. Southwestern warmth.",
    bestFor: "Regional trades and outdoor living",
    primary: "#b45f3a",
    secondary: "#fbf5ee",
    accent: "#d9a273",
    font: "Karla",
    fontNote: "Warm grotesque, easy body text",
    backdrop: "gradient_mesh",
    heroEffect: "rise",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["patio", "deck", "fence", "adobe", "stucco", "pool", "shade", "irrigat"],
  },
  {
    id: "graphite-gold",
    name: "Graphite gold",
    mood: "Graphite with restrained gold hairlines. Boardroom confidence.",
    bestFor: "High-value B2B services",
    primary: "#d6b370",
    secondary: "#121316",
    accent: "#f0dcae",
    font: "Playfair Display",
    fontNote: "Editorial serif headings, quiet body text",
    backdrop: "grid",
    heroEffect: "float_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["financ", "invest", "law", "advis", "broker", "wealth", "commercial", "consult"],
  },
  {
    id: "citrus-pop",
    name: "Citrus pop",
    mood: "White page, citrus yellow-green accents, playful but tidy.",
    bestFor: "Cleaning, delivery and everyday services",
    primary: "#4d7c0f",
    secondary: "#fdfef7",
    accent: "#a3e635",
    font: "Rubik",
    fontNote: "Rounded sans with friendly corners",
    backdrop: "none",
    heroEffect: "rise",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["clean", "maid", "deliver", "courier", "laundry", "grocer", "junk", "haul"],
  },
  {
    id: "deep-space",
    name: "Deep space",
    mood: "Starfield over blue-black with cool cyan light. Futuristic calm.",
    bestFor: "Security, monitoring and tech installs",
    primary: "#22d3ee",
    secondary: "#060913",
    accent: "#a5f3fc",
    font: "Space Grotesk",
    fontNote: "Technical sans with character",
    backdrop: "stars",
    heroEffect: "float_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "parallax_slow",
    affinity: ["security", "camera", "monitor", "alarm", "network", "drone", "satellite", "smart"],
  },
  {
    id: "paper-navy",
    name: "Paper navy",
    mood: "Bright paper with navy type and a red seal accent. Official and clear.",
    bestFor: "Inspection, compliance and advisory work",
    primary: "#1e3a5f",
    secondary: "#fbfbf9",
    accent: "#c0392b",
    font: "IBM Plex Sans",
    fontNote: "Institutional, dependable",
    backdrop: "none",
    heroEffect: "rise",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["inspect", "survey", "compliance", "audit", "engineer", "appraise", "permit"],
  },
  {
    id: "neon-court",
    name: "Neon court",
    mood: "Dark court blue with neon highlights. Athletic and energetic.",
    bestFor: "Gyms, coaching and sports services",
    primary: "#22c55e",
    secondary: "#0a1017",
    accent: "#facc15",
    font: "Anton",
    fontNote: "Heavyweight condensed headings",
    backdrop: "spotlight",
    heroEffect: "tilt_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["gym", "fitness", "sport", "coach", "train", "martial", "swim", "team"],
  },
  {
    id: "oat-terracotta",
    name: "Oat terracotta",
    mood: "Oat background with terracotta headings. Homely and hand-finished.",
    bestFor: "Home makers, cafés and small-batch producers",
    primary: "#a3431f",
    secondary: "#f8f4ec",
    accent: "#e0885f",
    font: "Lora",
    fontNote: "Warm serif headings, easy body text",
    backdrop: "none",
    heroEffect: "rise",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["cafe", "bake", "ceramic", "pottery", "market", "craft", "candle", "soap"],
  },
  {
    id: "tungsten-blue",
    name: "Tungsten blue",
    mood: "Dark tungsten grey with a cold blue edge. Engineering seriousness.",
    bestFor: "Electrical, controls and industrial services",
    primary: "#60a5fa",
    secondary: "#101215",
    accent: "#bfdbfe",
    font: "Schibsted Grotesk",
    fontNote: "Sharp technical grotesque",
    backdrop: "grid",
    heroEffect: "rise",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["electric", "control", "panel", "automation", "machin", "industrial", "wiring"],
  },
  {
    id: "seafoam-calm",
    name: "Seafoam calm",
    mood: "Seafoam tints on white with soft cards. Reassuring and tidy.",
    bestFor: "Care, admin and family services",
    primary: "#0d9488",
    secondary: "#f3fbf9",
    accent: "#5eead4",
    font: "Manrope",
    fontNote: "Soft geometric sans, wide spacing",
    backdrop: "gradient_mesh",
    heroEffect: "rise",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["care", "senior", "nurs", "admin", "book keep", "insur", "school", "nanny"],
  },
  {
    id: "onyx-ivory",
    name: "Onyx ivory",
    mood: "Onyx surfaces with ivory serif type. Gallery quiet.",
    bestFor: "Design-led studios and fine work",
    primary: "#ece7dd",
    secondary: "#0e0e0f",
    accent: "#bfa06a",
    font: "Instrument Serif",
    fontNote: "Display serif headlines, plain body",
    backdrop: "spotlight",
    heroEffect: "parallax_slow",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "shine",
    affinity: ["gallery", "art", "architect", "photo", "jewel", "tailor", "antique", "studio"],
  },
  {
    id: "meadow-light",
    name: "Meadow light",
    mood: "Daylight white with meadow greens and airy sections.",
    bestFor: "Garden, florist and seasonal businesses",
    primary: "#15803d",
    secondary: "#fafdf7",
    accent: "#86efac",
    font: "Figtree",
    fontNote: "Friendly rounded sans",
    backdrop: "none",
    heroEffect: "rise",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["garden", "florist", "nursery", "plant", "lawn", "seed", "allotment", "bee"],
  },
  {
    id: "charcoal-signal",
    name: "Charcoal signal",
    mood: "Charcoal with one hot signal colour on every action.",
    bestFor: "Lead-hungry services that need clicks now",
    primary: "#ef4444",
    secondary: "#141416",
    accent: "#fca5a5",
    font: "Archivo Black",
    fontNote: "Big impact headings, tight body copy",
    backdrop: "gradient_mesh",
    heroEffect: "tilt_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["roof", "pest", "septic", "drain", "mold", "asbestos", "junk", "claim"],
  },
  {
    id: "porcelain-blue",
    name: "Porcelain blue",
    mood: "Porcelain surfaces, delft blue accents, very legible.",
    bestFor: "Trades where tidiness is the product",
    primary: "#1d4ed8",
    secondary: "#ffffff",
    accent: "#93c5fd",
    font: "Inter",
    fontNote: "Neutral, highly readable at every size",
    backdrop: "none",
    heroEffect: "rise",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["tile", "bath", "kitchen", "paint", "plaster", "floor", "glaz", "shower"],
  },
  {
    id: "amber-night",
    name: "Amber night",
    mood: "Warm dark browns with amber lamps. Evening hospitality.",
    bestFor: "Restaurants, bars and evening trades",
    primary: "#f59e0b",
    secondary: "#14100c",
    accent: "#fde68a",
    font: "Fraunces",
    fontNote: "Characterful serif with warmth",
    backdrop: "spotlight",
    heroEffect: "float_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "shine",
    affinity: ["restaur", "bar", "pub", "grill", "pizza", "cater", "food", "brew"],
  },
  {
    id: "ice-graphite",
    name: "Ice graphite",
    mood: "Icy neutral page, graphite type, one cold accent. Zero clutter.",
    bestFor: "Anyone who wants clarity above personality",
    primary: "#334155",
    secondary: "#f6f7f9",
    accent: "#0ea5e9",
    font: "Geist",
    fontNote: "Precise modern sans",
    backdrop: "none",
    heroEffect: "rise",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["it", "support", "repair", "device", "print", "office", "courier", "storage"],
  },
  {
    id: "royal-indigo",
    name: "Royal indigo",
    mood: "Royal indigo with gold hairlines. Ceremony without stuffiness.",
    bestFor: "Formal services and milestone occasions",
    primary: "#c7a253",
    secondary: "#0b0f1f",
    accent: "#dbc07f",
    font: "Cormorant Garamond",
    fontNote: "Elegant high-contrast serif",
    backdrop: "stars",
    heroEffect: "float_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["funeral", "memorial", "wedding", "legal", "chapel", "academy", "society"],
  },
  {
    id: "mint-studio",
    name: "Mint studio",
    mood: "Cool mint tints, generous cards, bright and modern.",
    bestFor: "New businesses wanting a fresh, current look",
    primary: "#059669",
    secondary: "#f4fdf9",
    accent: "#34d399",
    font: "Plus Jakarta Sans",
    fontNote: "Rounded, friendly, very legible",
    backdrop: "gradient_mesh",
    heroEffect: "rise",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["startup", "studio", "app", "subscription", "eco", "recycl", "vegan", "zero"],
  },
  {
    id: "smoke-rose",
    name: "Smoke rose",
    mood: "Smoked charcoal with dusty rose. Soft edge on a dark page.",
    bestFor: "Beauty and lifestyle brands that want depth",
    primary: "#fb7185",
    secondary: "#151013",
    accent: "#fecdd3",
    font: "Epilogue",
    fontNote: "Elegant variable sans",
    backdrop: "nebula",
    heroEffect: "float_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "shine",
    affinity: ["beauty", "lash", "nail", "aesthetic", "skin", "hair", "makeup", "boudoir"],
  },
  {
    id: "field-khaki",
    name: "Field khaki",
    mood: "Khaki and olive on warm paper. Practical, outdoor, trustworthy.",
    bestFor: "Field services and rural contracts",
    primary: "#4d5c2c",
    secondary: "#f7f6ef",
    accent: "#a3a55c",
    font: "Work Sans",
    fontNote: "Neutral workhorse sans",
    backdrop: "none",
    heroEffect: "rise",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["agri", "farm", "fence", "drill", "well", "survey", "forest", "equip"],
  },
  {
    id: "titanium-violet",
    name: "Titanium violet",
    mood: "Titanium greys lit by violet. Understated future-facing polish.",
    bestFor: "Specialist installers and modern studios",
    primary: "#8b5cf6",
    secondary: "#101014",
    accent: "#c4b5fd",
    font: "Outfit",
    fontNote: "Geometric sans, clean headings",
    backdrop: "aurora",
    heroEffect: "float_3d",
    ctaEffect: "gold_glow",
    formEffect: "glass",
    bodyEffect: "parallax_slow",
    affinity: ["audio", "cinema", "lighting", "smart", "ev", "install", "studio", "stage"],
  },
  {
    id: "canvas-black",
    name: "Canvas black",
    mood: "Gallery-white canvas, black type, photography does the talking.",
    bestFor: "Portfolio-first businesses",
    primary: "#0a0a0a",
    secondary: "#fbfbfb",
    accent: "#6b7280",
    font: "Bricolage Grotesque",
    fontNote: "Expressive display grotesque",
    backdrop: "none",
    heroEffect: "parallax_slow",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["photo", "video", "portfolio", "paint", "stage", "model", "print", "sign"],
  },
  {
    id: "harvest-gold",
    name: "Harvest gold",
    mood: "Warm harvest tones on soft cream. Seasonal and generous.",
    bestFor: "Food, farm shops and seasonal services",
    primary: "#92400e",
    secondary: "#fdf6e9",
    accent: "#d97706",
    font: "Spectral",
    fontNote: "Readable literary serif",
    backdrop: "none",
    heroEffect: "rise",
    ctaEffect: "rise",
    formEffect: "glass",
    bodyEffect: "rise",
    affinity: ["farm", "butcher", "deli", "cider", "honey", "market", "orchard", "cheese"],
  },
];

const hash = (value: string) => {
  let out = 2166136261;
  for (let i = 0; i < value.length; i += 1) {
    out ^= value.charCodeAt(i);
    out = Math.imul(out, 16777619) >>> 0;
  }
  return out;
};

/**
 * Ranks directions for this specific business. Industry words come first, then
 * a stable per-business seed decides the rest — so two identical trades in the
 * same town still get offered different identities.
 */
export function recommendDirections(input: {
  businessName: string | null;
  industry: string | null;
  services: { name: string }[];
  city: string | null;
  currentFont?: string | null;
  count?: number;
  /** Bump to shuffle in a completely fresh set of elite options. */
  refresh?: number;
  /** Set to "light" or "dark" to only offer directions of that tone. */
  tone?: "light" | "dark" | "any";
}): DesignDirection[] {
  const words = [input.industry ?? "", ...input.services.map((service) => service.name)]
    .join(" ")
    .toLowerCase();
  const seed = hash(
    `${input.businessName ?? ""}|${input.industry ?? ""}|${input.city ?? ""}|${input.refresh ?? 0}`,
  );
  const pool =
    !input.tone || input.tone === "any"
      ? DESIGN_DIRECTIONS
      : DESIGN_DIRECTIONS.filter((direction) => directionTone(direction) === input.tone);

  const scored = pool
    .map((direction, index) => {
      const matches = direction.affinity.filter((word) => words.includes(word)).length;
      const jitter = (hash(`${direction.id}:${seed}`) % 100) / 100;
      const current =
        input.currentFont && direction.font.toLowerCase() === input.currentFont.toLowerCase()
          ? 0.4
          : 0;
      return { direction, score: matches * 2 + jitter + current, index };
    })
    .sort((a, b) => b.score - a.score || a.index - b.index);

  return scored.slice(0, input.count ?? 4).map((entry) => entry.direction);
}

/** The exact, reversible changes that installing a direction makes. */
export function directionActions(direction: DesignDirection, pages: ContentPage[]): AgentAction[] {
  const actions: AgentAction[] = [
    {
      type: "set_theme",
      patch: {
        primary_color: direction.primary,
        secondary_color: direction.secondary,
        accent_color: direction.accent,
        font_preference: direction.font,
      },
    },
    { type: "set_backdrop", backdrop: direction.backdrop },
  ];

  const sections = pages
    .filter((page) => page.is_visible)
    .flatMap((page) => page.sections.filter((section) => section.is_visible))
    .slice(0, 40);

  for (const section of sections) {
    const effect =
      section.kind === "hero"
        ? direction.heroEffect
        : section.kind === "cta" || section.kind === "sticky_cta" || section.kind === "offer"
          ? direction.ctaEffect
          : section.kind === "quote" || section.kind === "booking" || section.kind === "contact"
            ? direction.formEffect
            : direction.bodyEffect;
    actions.push({ type: "set_section_effect", sectionId: section.id, effect });
  }

  return actions;
}

/** Whether a direction renders as a light (white/pale) or dark website. */
export function directionTone(direction: DesignDirection): "light" | "dark" {
  return siteTone(direction.secondary);
}

/** Plain-language preview of what a direction changes. */
export function directionPreview(direction: DesignDirection, sectionCount: number): string[] {
  return [
    `Overall look → ${directionTone(direction) === "light" ? "light, white-page website" : "dark, high-contrast website"}`,
    `Brand colours → ${direction.primary} with ${direction.accent}`,
    `Headings → ${direction.font} (${direction.fontNote})`,
    `Background → ${direction.backdrop === "none" ? "clean, no animation" : direction.backdrop.replace(/_/g, " ")}`,
    `Motion → ${sectionCount} section${sectionCount === 1 ? "" : "s"} restyled (hero ${direction.heroEffect.replace(/_/g, " ")}, buttons ${direction.ctaEffect.replace(/_/g, " ")})`,
  ];
}
