import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // `src/integrations/supabase/*` is generated and regenerated by the platform,
  // so it is not hand-editable and is excluded from lint.
  { ignores: ["dist", ".output", ".vinxi", "src/integrations/supabase/**"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  // These files intentionally use low-level sentinels/control-character
  // handling and one test fixture uses a structural context cast. Keep those
  // narrow exceptions local instead of weakening lint across the repository.
  {
    files: [
      "src/lib/builder/autonomous-brain.test.ts",
      "src/lib/builder/copy.ts",
      "src/lib/builder/literal.ts",
      "src/lib/builder/local-inference.ts",
      "src/lib/builder/presentation.ts",
    ],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "no-control-regex": "off",
      "prefer-const": "off",
    },
  },
);