import type { ConnectorDefinition } from "./types";

/**
 * Registry is intentionally metadata-only. Secrets are never hard-coded and
 * third-party providers are activated only after the user connects them.
 */
export const CONNECTORS: ConnectorDefinition[] = [
  {
    id: "supabase",
    name: "Supabase",
    category: "infrastructure",
    status: "connected",
    freeFirst: true,
    requiredSecrets: [],
    capabilities: ["database", "auth", "storage", "edge_functions", "realtime"],
  },
  {
    id: "internal-website-audit",
    name: "Revora Native Website Audit",
    category: "website",
    status: "connected",
    freeFirst: true,
    requiredSecrets: [],
    capabilities: ["url_validation", "html_audit", "seo_signals", "accessibility_signals", "performance_signals"],
  },
  {
    id: "n8n",
    name: "n8n",
    category: "automation",
    status: "not_connected",
    freeFirst: true,
    requiredSecrets: ["N8N_BASE_URL", "N8N_WEBHOOK_SECRET"],
    capabilities: ["workflow_webhooks", "lead_follow_up", "booking_automation", "review_requests"],
  },
  {
    id: "google-analytics",
    name: "Google Analytics",
    category: "analytics",
    status: "not_connected",
    freeFirst: true,
    requiredSecrets: ["GOOGLE_ANALYTICS_PROPERTY_ID", "GOOGLE_SERVICE_ACCOUNT_JSON"],
    capabilities: ["traffic", "engagement", "conversion_measurement"],
  },
  {
    id: "google-search-console",
    name: "Google Search Console",
    category: "seo",
    status: "not_connected",
    freeFirst: true,
    requiredSecrets: ["GOOGLE_SEARCH_CONSOLE_SITE_URL", "GOOGLE_SERVICE_ACCOUNT_JSON"],
    capabilities: ["queries", "impressions", "clicks", "ctr", "position"],
  },
  {
    id: "wordpress",
    name: "WordPress",
    category: "website",
    status: "not_connected",
    freeFirst: true,
    requiredSecrets: ["WORDPRESS_BASE_URL", "WORDPRESS_APPLICATION_PASSWORD"],
    capabilities: ["site_audit", "authorized_content_updates", "publishing"],
  },
  {
    id: "wix",
    name: "Wix",
    category: "website",
    status: "not_connected",
    freeFirst: true,
    requiredSecrets: ["WIX_ACCESS_TOKEN"],
    capabilities: ["site_audit", "authorized_content_updates"],
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    category: "calendar",
    status: "not_connected",
    freeFirst: true,
    requiredSecrets: ["GOOGLE_CALENDAR_CREDENTIALS"],
    capabilities: ["availability", "booking_sync", "reminders"],
  },
  {
    id: "calendly",
    name: "Calendly",
    category: "calendar",
    status: "not_connected",
    freeFirst: true,
    requiredSecrets: ["CALENDLY_ACCESS_TOKEN"],
    capabilities: ["booking_events", "appointment_sync"],
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "payments",
    status: "connected",
    freeFirst: true,
    requiredSecrets: ["STRIPE_SECRET_KEY", "STRIPE_WEBHOOK_SECRET"],
    capabilities: ["subscriptions", "payments", "billing_events"],
  },
  {
    id: "twilio",
    name: "Twilio",
    category: "messaging",
    status: "not_connected",
    freeFirst: false,
    requiredSecrets: ["TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN"],
    capabilities: ["sms", "voice", "reminders"],
  },
  {
    id: "resend",
    name: "Resend",
    category: "messaging",
    status: "not_connected",
    freeFirst: true,
    requiredSecrets: ["RESEND_API_KEY"],
    capabilities: ["transactional_email", "lifecycle_email"],
  },
  {
    id: "firecrawl",
    name: "Firecrawl",
    category: "website",
    status: "not_connected",
    freeFirst: false,
    requiredSecrets: ["FIRECRAWL_API_KEY"],
    capabilities: ["deep_crawl", "rendered_pages", "structured_extraction"],
  },
  {
    id: "canva",
    name: "Canva",
    category: "creative",
    status: "not_connected",
    freeFirst: true,
    requiredSecrets: ["CANVA_ACCESS_TOKEN"],
    capabilities: ["creative_assets", "templates"],
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "infrastructure",
    status: "not_connected",
    freeFirst: true,
    requiredSecrets: ["CLOUDFLARE_API_TOKEN", "CLOUDFLARE_ZONE_ID"],
    capabilities: ["dns", "domains", "edge_security", "caching"],
  },
];

export function getConnector(id: string) {
  return CONNECTORS.find((connector) => connector.id === id) ?? null;
}
