/**
 * Website picture records (spec D).
 *
 * One record per picture slot ("home:hero", "services:card-2"…) with its art
 * direction, approval state and verified rendered URL. Pure state machine:
 * no network, so the server functions, UI and tests share the same rules.
 *
 *   pending ──approve──▶ approved
 *      │  ╲                 │
 *   reject  regenerate   regenerate
 *      ▼        ▼           ▼
 *   rejected ─regenerate─▶ regenerating ──success──▶ pending (generation+1)
 *                               └────────failure──▶ failed ─regenerate─▶ …
 *
 * Owner photos are never regenerated by the AI. A rendered URL is only
 * recorded as verified after a real fetch returned an image content type.
 */

export const IMAGE_STATUSES = ["pending", "approved", "rejected", "regenerating", "failed"] as const;
export type ImageStatus = (typeof IMAGE_STATUSES)[number];
export type ImageAction = "approve" | "reject" | "regenerate" | "regenerated" | "regenerate_failed";

export type ImageRecordState = {
  status: ImageStatus;
  source: "generated" | "owner" | "stock";
  generation: number;
};

export type Transition =
  | { ok: true; status: ImageStatus; generation: number }
  | { ok: false; reason: string };

const SLOT = /^[a-z0-9][a-z0-9:_-]{0,79}$/;

/** A normalised slot key, or null when it can't be stored. */
export function normaliseSlot(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const slot = value.trim().toLowerCase();
  return SLOT.test(slot) ? slot : null;
}

export function transitionImage(state: ImageRecordState, action: ImageAction): Transition {
  const { status, source, generation } = state;
  switch (action) {
    case "approve":
      if (status === "pending" || status === "rejected") return { ok: true, status: "approved", generation };
      if (status === "approved") return { ok: false, reason: "This picture is already approved." };
      return { ok: false, reason: "Wait for the new picture before approving it." };
    case "reject":
      if (status === "pending" || status === "approved") return { ok: true, status: "rejected", generation };
      if (status === "rejected") return { ok: false, reason: "This picture is already rejected." };
      return { ok: false, reason: "Wait for the new picture before rejecting it." };
    case "regenerate":
      if (source === "owner") return { ok: false, reason: "Your own photos are never replaced by AI pictures." };
      if (status === "regenerating") return { ok: false, reason: "A new picture is already being made." };
      return { ok: true, status: "regenerating", generation };
    case "regenerated":
      if (status !== "regenerating") return { ok: false, reason: "No new picture was requested." };
      return { ok: true, status: "pending", generation: generation + 1 };
    case "regenerate_failed":
      if (status !== "regenerating") return { ok: false, reason: "No new picture was requested." };
      return { ok: true, status: "failed", generation };
  }
}

/**
 * The brief for a single-picture regeneration: the recorded art direction,
 * plus the owner's rejection reason as an explicit correction. Never invents
 * facts about the business; it only restates what was recorded.
 */
export function regenerationBrief(direction: string, rejectionReason?: string | null, extra?: string | null): string {
  const parts = [direction.trim()];
  if (rejectionReason?.trim()) parts.push(`The previous picture was rejected because: ${rejectionReason.trim()}. Correct that.`);
  if (extra?.trim()) parts.push(extra.trim());
  parts.push("Photorealistic, no text, no logos, no watermarks, no invented signage.");
  return parts.filter(Boolean).join("\n\n").slice(0, 4000);
}

/** True when an HTTP response proves the URL renders an image. */
export function isRenderableImageResponse(status: number, contentType: string | null | undefined): boolean {
  return status >= 200 && status < 300 && /^image\//i.test(String(contentType ?? ""));
}

/** Readiness summary for launch checks: every generated picture approved or owner-supplied. */
export function imageApprovalSummary(records: readonly { status: ImageStatus; source: string }[]): {
  total: number;
  approved: number;
  needsReview: number;
  failed: number;
  allApproved: boolean;
} {
  const total = records.length;
  const approved = records.filter((r) => r.status === "approved" || r.source === "owner").length;
  const failed = records.filter((r) => r.status === "failed").length;
  const needsReview = total - approved - failed;
  return { total, approved, needsReview, failed, allApproved: total > 0 && approved === total };
}
