/**
 * CINEMATIC VIDEO LANE (Sora)
 * ===========================
 *
 * One short, silent, looping clip for a website section, generated by OpenAI's
 * video models and accounted against the SAME durable monthly spending cap as
 * every other paid call. Rules that keep this safe rather than reckless:
 *
 *  1. off unless the paid lane as a whole is enabled and an OpenAI key exists,
 *     and an operator can switch it off outright with `PAID_VIDEO_ENABLED=false`,
 *  2. every clip is reserved against the durable cap BEFORE the call and settled
 *     after it, so there is no silent overage and no auto-top-up,
 *  3. failure is always reported as a precise reason — never a fabricated clip,
 *     never a silent swap to a picture,
 *  4. the model is pinned by name and proven by the account's own response; a
 *     model the project cannot reach is reported as a blocker.
 *
 * Server-only. The key is read inside functions and never returned to a caller.
 */

import { rosterEntry } from "@/lib/ai/openai-roster";
import { callPinnedPaidVideo } from "@/lib/ai/router.server";
import {
  MICROCENTS_PER_DOLLAR,
  formatUsd,
  lunaEnabled,
  lunaMonthlyCapMicrocents,
  recordUsage,
  reserveBudget,
  settleBudget,
} from "@/lib/ai/luna.server";

/** How long one job may take before Revora stops waiting, and the poll gap. */
const MAX_WAIT_MS = 8 * 60 * 1000;
const POLL_MS = 5_000;


export const VIDEO_TIERS = ["standard", "premium"] as const;
export type VideoTier = (typeof VIDEO_TIERS)[number];

const TIER_MODEL: Record<VideoTier, string> = {
  standard: "sora-2",
  premium: "sora-2-pro",
};

const DEFAULT_PRICE_USD: Record<VideoTier, number> = {
  standard: 0.6,
  premium: 1.8,
};

export type PaidVideoBlockReason =
  | "disabled"
  | "no_key"
  | "budget_exhausted"
  | "ledger_unavailable"
  | "model_unavailable"
  | "timed_out"
  | "provider_error"
  | "invalid_video";

export type PaidVideoResult =
  | {
      ok: true;
      bytes: Uint8Array;
      mimeType: "video/mp4";
      model: string;
      tier: VideoTier;
      seconds: number;
      costMicrocents: number;
    }
  | { ok: false; reason: PaidVideoBlockReason; message: string };

function env(name: string): string | null {
  const value = process.env[name];
  return typeof value === "string" && value.trim().length > 0 ? value.trim() : null;
}

function switchedOff(name: string): boolean {
  const raw = (env(name) ?? "").toLowerCase();
  return raw === "false" || raw === "0" || raw === "off" || raw === "no";
}

export function paidVideoModel(tier: VideoTier = "standard"): string {
  return env(tier === "premium" ? "PAID_VIDEO_MODEL_PREMIUM" : "PAID_VIDEO_MODEL") ?? TIER_MODEL[tier];
}

export function paidVideoPriceMicrocents(tier: VideoTier = "standard"): number {
  const raw = Number(env("PAID_VIDEO_PRICE_USD") ?? Number.NaN);
  const dollars = Number.isFinite(raw) && raw > 0 ? raw : DEFAULT_PRICE_USD[tier];
  return Math.round(dollars * MICROCENTS_PER_DOLLAR);
}

/** Plain-language status, safe to show a business owner. No secrets. */
export function paidVideoStatus(): { allowed: boolean; message: string } {
  if (switchedOff("PAID_VIDEO_ENABLED"))
    return { allowed: false, message: "Moving backgrounds are switched off for this workspace." };
  if (!lunaEnabled())
    return {
      allowed: false,
      message: "Moving backgrounds are not available in this workspace, so sections keep their photograph.",
    };
  if (!env("OPENAI_API_KEY"))
    return {
      allowed: false,
      message: "Moving-background generation is not connected, so sections keep their photograph.",
    };
  return {
    allowed: true,
    message: `Moving backgrounds can be generated inside the monthly spending cap of ${formatUsd(
      lunaMonthlyCapMicrocents(),
    )}.`,
  };
}

export type PaidVideoJob = {
  prompt: string;
  tier?: VideoTier;
  /** Requested clip length in seconds; the model serves the nearest it offers. */
  seconds?: number;
  size?: "1280x720" | "1792x1024" | "720x1280";
};


/**
 * Makes ONE clip, fully accounted against the durable cap. Never throws: every
 * failure comes back as a precise blocked reason so the caller can keep the
 * existing picture and tell the owner the truth.
 */
export async function generateSiteVideo(
  job: PaidVideoJob,
  caller: { organizationId: string | null; userId?: string | null },
): Promise<PaidVideoResult> {
  const status = paidVideoStatus();
  if (!status.allowed)
    return {
      ok: false,
      reason: switchedOff("PAID_VIDEO_ENABLED") || !lunaEnabled() ? "disabled" : "no_key",
      message: status.message,
    };

  const apiKey = env("OPENAI_API_KEY");
  if (!apiKey)
    return { ok: false, reason: "no_key", message: status.message };

  const tier: VideoTier = job.tier === "premium" ? "premium" : "standard";
  const model = paidVideoModel(tier);
  const entry = rosterEntry(model);
  if (entry?.blockedReason)
    return {
      ok: false,
      reason: "model_unavailable",
      message: `The moving-background model is not available yet (${entry.blockedReason}). Nothing was charged.`,
    };

  const seconds = job.seconds && job.seconds >= 4 && job.seconds <= 12 ? Math.round(job.seconds) : 8;
  const estimate = paidVideoPriceMicrocents(tier);
  const reservation = await reserveBudget(estimate, caller.organizationId);
  if (!reservation)
    return {
      ok: false,
      reason: "ledger_unavailable",
      message: "Revora could not confirm the spending cap, so no moving background was made.",
    };
  if (!reservation.allowed) {
    await recordUsage({
      organizationId: caller.organizationId,
      purpose: "video_generation",
      model,
      usage: { inputTokens: 0, cachedInputTokens: 0, outputTokens: 0 },
      cost: 0,
      outcome: "skipped",
      reason: "budget_exhausted",
    });
    return {
      ok: false,
      reason: "budget_exhausted",
      message: `This month's ${formatUsd(reservation.cap)} allowance is used up, so no moving background was made. Nothing extra was charged.`,
    };
  }

  const fail = async (
    reason: PaidVideoBlockReason,
    message: string,
    charged: number,
  ): Promise<PaidVideoResult> => {
    await settleBudget(caller.organizationId, estimate, charged);
    await recordUsage({
      organizationId: caller.organizationId,
      purpose: "video_generation",
      model,
      usage: { inputTokens: 0, cachedInputTokens: 0, outputTokens: 0 },
      cost: charged,
      outcome: "failed",
      reason,
    });
    return { ok: false, reason, message };
  };

  const MESSAGES: Record<"model_unavailable" | "provider_error" | "timed_out" | "invalid_video", string> =
    {
      model_unavailable: "This account cannot use the moving-background model yet",
      provider_error: "The moving background could not be rendered",
      timed_out: "The moving background took too long to render, so the section kept its picture",
      invalid_video: "The returned clip was empty, so nothing was saved",
    };

  try {
    const outcome = await callPinnedPaidVideo(
      { organizationId: caller.organizationId, userId: caller.userId ?? null },
      { model, prompt: job.prompt, seconds, size: job.size ?? "1280x720" },
      { maxWaitMs: MAX_WAIT_MS, pollMs: POLL_MS },
    );
    if (!outcome.ok)
      return await fail(
        outcome.kind,
        `${MESSAGES[outcome.kind]} (${outcome.detail}).${
          outcome.charged ? "" : " Nothing was charged."
        }`,
        outcome.charged ? estimate : 0,
      );

    await settleBudget(caller.organizationId, estimate, estimate);
    await recordUsage({
      organizationId: caller.organizationId,
      purpose: "video_generation",
      model,
      usage: { inputTokens: 0, cachedInputTokens: 0, outputTokens: 0 },
      cost: estimate,
      outcome: "succeeded",
      reason: null,
    });
    return {
      ok: true,
      bytes: outcome.bytes,
      mimeType: "video/mp4",
      model,
      tier,
      seconds,
      costMicrocents: estimate,
    };
  } catch {
    return await fail(
      "provider_error",
      "The moving-background service could not be reached. Nothing was charged.",
      0,
    );
  }
}

